import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeSwitchProvider } from '@/providers/ThemeSwitchProvider'
import Navbar from '@/components/Navbar'
import { StoreProvider } from '@/providers/StoreProvider'
import { ToastContainer } from 'react-toastify'
import "react-toastify/dist/ReactToastify.css";
import DeleteConfirmationModal from '@/components/DeleteConfirmationModal'
import { SpeedInsights } from "@vercel/speed-insights/next"
import { Analytics } from '@vercel/analytics/react';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'AuthGuardian',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='min-h-screen w-full relative bg-gray-100 dark:bg-gray-900'>
          <StoreProvider>
            <ThemeSwitchProvider>
              <DeleteConfirmationModal/>
              <Navbar />
              {children}
              <ToastContainer/>
            </ThemeSwitchProvider>
          </StoreProvider>
        </div>
        <Analytics/>
        <SpeedInsights/>  
      </body>
    </html>
  )
}
